version: 3
automerge: true
autodiscover:
  mode: auto
parallel_plan: true
parallel_apply: true
abort_on_execution_order_fail: true
projects:
  - name: artifacts.k8s.io
    branch: /main/
    dir: infra/aws/terraform/artifacts.k8s.io
    workflow: aws
# For AWS, atlantis needs to assume a specific role in each account except the management account
# so we read it from the folder that atlantis will work on
workflows:
  aws:
    plan:
      steps:
        - init:
            extra_args: ["--backend-config", "atlantis.config"]
        - plan:
            extra_args: ["-var-file", "atlantis.tfvars"]
    apply:
      steps:
        - apply:
            extra_args: ["-var-file", "atlantis.tfvars"]
    import:
      steps:
        - init:
            extra_args: ["--backend-config", "atlantis.config"]
        - import:
            extra_args: ["-var-file", "atlantis.tfvars"]
