apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: datadog-secret
spec:
  dataFrom:
    - extract:
        key: datadog-secrets
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow-build
