apiVersion: v1
kind: Secret
metadata:
  name: gke-prow
  labels:
    argocd.argoproj.io/secret-type: cluster
    clusterType: prow
    environment: prod
    prowNamespace: default
    cloud: gke
type: Opaque
stringData:
  name: gke-prow
  server: https://10.254.0.18
  config: |
    {
      "execProviderConfig": {
        "command": "argocd-k8s-auth",
        "args": ["gcp"],
        "apiVersion": "client.authentication.k8s.io/v1beta1"
      },
      "tlsClientConfig": {
        "insecure": true
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: gke-prow-build
  labels:
    argocd.argoproj.io/secret-type: cluster
    clusterType: prow
    environment: prod
    prowNamespace: test-pods
    cloud: gke
type: Opaque
stringData:
  name: gke-prow-build
  server: https://gke-8d7225b757872b0f06a6e02c3ea8b5713dc9-773781448124.us-central1.gke.goog
  config: |
    {
      "execProviderConfig": {
        "command": "argocd-k8s-auth",
        "args": ["gcp"],
        "apiVersion": "client.authentication.k8s.io/v1beta1"
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: gke-prow-build-trusted
  labels:
    argocd.argoproj.io/secret-type: cluster
    clusterType: prow
    environment: prod
    prowNamespace: test-pods
    cloud: gke
type: Opaque
stringData:
  name: gke-prow-build-trusted
  server: https://gke-8f83dcb7a83817de24081addbc0b670b3dd4-180382678033.us-central1.gke.goog
  config: |
    {
      "execProviderConfig": {
        "command": "argocd-k8s-auth",
        "args": ["gcp"],
        "apiVersion": "client.authentication.k8s.io/v1beta1"
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: gke-aaa
  labels:
    argocd.argoproj.io/secret-type: cluster
    clusterType: apps
    environment: prod
    cloud: gke
type: Opaque
stringData:
  name: gke-aaa
  server: https://gke-4d0eb7639c079dd868639801ff9cee7661c5-127754664067.us-central1.gke.goog
  config: |
    {
      "execProviderConfig": {
        "command": "argocd-k8s-auth",
        "args": ["gcp"],
        "apiVersion": "client.authentication.k8s.io/v1beta1"
      }
    }
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ibm-ppc64le
spec:
  target:
    template:
      engineVersion: v2
      data:
        name: ibm-ppc64le
        server: https://73725434-jp-osa.lb.appdomain.cloud:6443
        config: "{{ .config }}"
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
          clusterType: prow
          environment: prod
          prowNamespace: test-pods
          cloud: ibm
  data:
    - remoteRef:
        key: ibm-ppc64le-argo-secret
      secretKey: config
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ibm-s390x
spec:
  target:
    template:
      engineVersion: v2
      data:
        name: ibm-s390x
        server: https://d7b2a019-eu-de.lb.appdomain.cloud:6443
        config: "{{ .config }}"
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
          clusterType: prow
          environment: prod
          prowNamespace: test-pods
          cloud: ibm
  data:
    - remoteRef:
        key: ibm-s390x-argo-secret
      secretKey: config
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow
---
apiVersion: v1
kind: Secret
metadata:
  name: eks-prow-kops
  labels:
    argocd.argoproj.io/secret-type: cluster
    clusterType: prow
    environment: prod
    prowNamespace: test-pods
    cloud: eks
type: Opaque
stringData:
  name: eks-prow-kops
  server: https://7283E85C59E9C4129CFD07BAC9378D44.gr7.us-east-2.eks.amazonaws.com
  config: |
    {
      "awsAuthConfig": {
        "clusterName": "k8s-infra-kops-prow-build"
      },
      "tlsClientConfig": {
        "insecure": true
      }
    }
